Merge packer-base to master
Otus-DevOps-2017-11/AndreyZhelezov_infra pull request #3
Opened 2017-12-25 14:58 UTC by AndreyZhelezov

Запрос на добавление ДЗ №7 в ветку master.

2017-12-25 16:50 UTC, vitkhab requested changes
Требуется определиться с тем, какой образ используется за базовый: ubuntu или debian; и доработать проект, чтобы из шаблона `immutable.json` успешно собирался образ.
В документацию можно добавить дополнительную информацию о проекте, как его запустит, как проверить.  Как пример хорошо описанной документации - https://goo.gl/me4MEX

2017-12-25 16:50 UTC, vitkhab commented on packer/variables.json.example
> +  "s_im_fam": "debian-8",
Мне, как пользователю, не понятно какой образ следует использовать: debian или ubuntu?

При сборке на базе `debian-8` требуется установка `git`. Упоминания об этом нигде не увидел.
При сборке `immutable.json` как на основе образа `ubuntu-1604-lts`, так и на основе `debian-8` я получаю ошибку
```
    googlecompute: cp: cannot create regular file '/etc/systemd/service/': Not a directory
    googlecompute: chmod: cannot access '/etc/systemd/service/puma.service': No such file or directory
    googlecompute: Failed to execute operation: No such file or directory
    googlecompute: Failed to start puma.service: Unit puma.service not found.
```

2017-12-25 16:50 UTC, vitkhab commented on packer/variables.json.example
> +  "snet_name": "projects/infra-555555/regions/europe-west1/subnetworks/network-name",
Сейчас этот атрибут мне видится как излишнее усложнение. Его обязательно надо поменять и значение не так чтобы очевидно.

2017-12-27 14:36 UTC, AndreyZhelezov commented on packer/variables.json.example
> +  "s_im_fam": "debian-8",
Проработал всё ДЗ заново. Позапускал всё ещё много раз. Теперь вроде работает. Долго мучался с настройкой сервиса автозапуска. Дополнил описание и постарался учесть в нем все замечания, но пример описания целенаправленно не читал больше одного раза, хотел по-своему сделать.

2017-12-27 14:38 UTC, AndreyZhelezov commented on packer/variables.json.example
> +  "snet_name": "projects/infra-555555/regions/europe-west1/subnetworks/network-name",
Атрибут сети задефолтил, т.к. сети другой не создавал, но если у кого-то она есть то он сможет её поменять. Надеюсь правильно понял замечание.

2017-12-28 15:05 UTC, vitkhab approved these changes
Все выполнено качественно. Спасибо за доработки!

2017-12-28 17:44 UTC, AndreyZhelezov commented
Спасибо за разъяснения. Не сразу разобрался с некоторыми моментами, да и доделывал "на бегу". Но после уточнений сразу стало всё понятно.

2017-12-28 17:46 UTC, merged