Merge terraform-2 to master.
Otus-DevOps-2017-11/AndreyZhelezov_infra pull request #5
Opened 2018-01-09 08:10 UTC by AndreyZhelezov

Прошу как и прошлое задание принять данную ДЗ №9 без учета заданий со звездочками.
Надеюсь что всё собрал правильно в данной ветке, и работоспособность всех конечных целей домашнего задания №9 будет стабильной. Уверенности в этом нет потому что изначальная конфигурация претерпевала значительное количество изменений, однако проверка на отдельном рабочем месте проблем не выявила. Инфраструктура собралась и в prod, и в stage, и в основном каталоге terraform storage-bucket.tf отработал нормально после замены имен баккетов на уникальные.
Вот только думаю я что данную ветку "terraform-2" нужно было создавать не от ветки "master", а от "terraform-1" тогда бы не было конфликтов при мердже с файлом README.md. К тому же есть такое ощущение что нужно было для данного ДЗ создать новый каталог, а не продолжать развивать старый "./terraform", потому что в процессе некоторые метаданные Terraform-а и переменные в файле terraform.tfvars вызывали несостыковки при перемещении между ветками "terraform-1" и "terraform-2". 
Частично эта путаница у меня в голове. И обусловлена она недостатком опыта ведения работы в системе контроля версий. Я даже подозреваю что требовался подход при котором документирование каждого этапа должно было сопровождаться коммитами промежуточных результатов, и даже пытался следовать этому принципу, но после некоторого времени понял что запутался и пересоздал ветку заново включив в нее только описание произведенных изменений и конечный результат. Поэтому заранее прошу прощения за такой, возможно трудный для восприятия результат.

2018-01-13 20:02 UTC, Nklya commented
Да, самый простой вариант - это начинать следующее задание от предыдущей ветки.
Другой вариант - дождаться принятия предыдущего дз, смержить в мастер и тогда начинать новый бранч.

Начинать это дз в новой папке не нужно. Потому что система контроля версий нормально все обрабатывает.

2018-01-13 20:10 UTC, Nklya requested changes
Добрый вечер.

Андрей, условия дз частично выполнены.

Не хватает работы с модулем storage-bucket, слайды 61-62.

Плюс, у тебя в ридми полностью отсутсвует форматирование.

2018-01-13 20:10 UTC, Nklya commented on terraform/stage/terraform.tfvars.example
> +disk_image		= "reddit-base"
disk_image был в предыдущем дз, в этом два образа, пример нужно обновить

2018-01-13 20:10 UTC, Nklya commented on terraform/prod/terraform.tfvars.example
> +disk_image		= "reddit-base"
disk_image был в предыдущем дз, в этом два образа, пример нужно обновить

2018-01-14 20:58 UTC, AndreyZhelezov commented on terraform/prod/terraform.tfvars.example
> +disk_image		= "reddit-base"
Исправил.

2018-01-14 20:58 UTC, AndreyZhelezov commented on terraform/stage/terraform.tfvars.example
> +disk_image		= "reddit-base"
Исправил.

2018-01-14 21:01 UTC, AndreyZhelezov commented
Исправил все замечания, если конечно правильно понял как отформатировать описание.
Дополнительно добавлены аутпут переменные которые пригодились при исполнении ДЗ №11 по Ansible.

2018-01-14 21:09 UTC, Nklya approved these changes
Добрый вечер.
Да, теперь все ок, помимо форматирования в ридми.

О чем это я говорю. 
Если ты окроешь https://github.com/Otus-DevOps-2017-11/AndreyZhelezov_infra/blob/terraform-2/README.md
то увидишь что оно представляет собой жуткую кашу, которую невозможно понять.

Вот пример нормального оформления https://github.com/Otus-DevOps-2017-11/f4rx_infra/blob/terraform-2/README.md

Можно не так сильно форматировать, но хотя бы так ок https://github.com/Otus-DevOps-2017-11/Raian13_infra/blob/terraform-2/README.md

2018-01-16 19:12 UTC, Nklya approved these changes
Вот теперь совсем другое дело.

2018-01-17 10:39 UTC, merged